import { ToolReview } from "@/lib/types";

export const gptZero: ToolReview = {
  slug: "gptzero",
  name: "GPTZero",
  tagline: "Leading AI content detector used by educators and publishers to identify AI-generated text",
  category: "ai-detection-tools",
  url: "https://gptzero.me",

  scores: {
    easeOfUse: 9,
    outputQuality: 7,
    value: 7,
    features: 7,
    overall: 7.5,
  },

  hasFreeTier: true,
  pricing: [
    {
      plan: "Free",
      price: "$0",
      features: [
        "5,000 words/month",
        "Single document scan",
        "Basic AI detection",
        "Sentence-level highlighting",
      ],
    },
    {
      plan: "Essential",
      price: "$10",
      period: "month",
      features: [
        "150,000 words/month",
        "Batch file uploads",
        "Detailed writing reports",
        "API access",
      ],
    },
    {
      plan: "Premium",
      price: "$16",
      period: "month",
      features: [
        "300,000 words/month",
        "Batch file uploads",
        "Full writing reports",
        "Plagiarism detection",
        "API access",
        "Priority support",
      ],
    },
  ],

  pros: [
    "Most accurate AI detector in independent benchmarks -- consistently beats Originality.ai and others",
    "Sentence-level highlighting shows exactly which parts triggered the detection, not just a score",
    "Dead simple interface -- paste text, get a result in seconds",
    "Free tier is generous enough for occasional checks without paying",
  ],
  cons: [
    "False positives are still a real problem -- human-written text gets flagged as AI more often than you'd expect",
    "Accuracy drops noticeably on heavily edited or paraphrased AI text",
    "No detection tool can reliably catch AI content that's been rewritten by a human, which limits usefulness",
    "Plagiarism checker is only on Premium and doesn't match Turnitin's depth",
  ],
  knownIssues: [
    {
      description: "Non-native English speakers' writing gets flagged as AI-generated at higher rates, raising fairness concerns",
      source: "Reddit r/professors",
      date: "2026-03",
    },
    {
      description: "Detection accuracy drops significantly on content generated by Claude and GPT-4o with custom instructions",
      source: "Reddit r/ChatGPT",
      date: "2026-02",
    },
    {
      description: "Batch upload feature occasionally fails silently on large PDF files",
      source: "G2 Reviews",
      date: "2026-01",
    },
  ],
  bestFor: "Educators who want a quick check on student submissions, and publishers who need a first-pass AI content screen.",
  notFor: "Anyone who expects 100% accuracy. No AI detector is reliable enough to be the sole basis for an accusation of cheating.",
  verdict: "GPTZero is the best AI detector available right now, but that's a low bar. It's more accurate than competitors and the sentence-level highlighting is genuinely useful. But false positives remain a serious issue, especially for non-native English writers. Use it as one signal among many, not as definitive proof. The fundamental problem is that AI detection is an arms race, and detectors are losing.",

  lastReviewedDate: "2026-04-02",
  dataSources: [
    { name: "GPTZero official site", dateAccessed: "2026-04-02" },
    { name: "Reddit r/professors", dateAccessed: "2026-04-02" },
    { name: "G2 Reviews", dateAccessed: "2026-04-02" },
    { name: "Independent accuracy benchmarks", dateAccessed: "2026-04-02" },
  ],
  affiliateUrl: "https://gptzero.me",
  status: "active",
  metaTitle: "GPTZero Review 2026: Most Accurate AI Detector?",
  metaDescription: "Honest GPTZero review with accuracy analysis, pricing, and known false positive issues. Best AI detection tool for educators? April 2026.",
};
